Repository NewSpring/crete, pull requests merged in 2020-03, with the labels that each got.

#61 chore: Fixes Travis deploy
  .travis.yml
Labels: merge

#62 chore: Removes unnecessary image code
  src/data/content-items/data-source.js
Labels: merge

#58 chore: Use Rock Schedules for Live Stream
  config.yml
  src/data/index.js
  src/data/live/data-source.js
  src/data/live/index.js
  src/data/live/resolver.js
Labels: merge

#55 chore: Removes custom code from auth
  src/data/auth/data-source.js
  src/data/auth/index.js
  src/data/index.js
Labels: merge

#63 feat: Adds Test Groups to Users
  config.yml
  src/data/groups/data-source.js
  src/data/groups/index.js
  src/data/groups/resolver.js
  src/data/groups/schema.js
  src/data/people/__tests__/resolvers.tests.js
  src/data/people/schema.js
  src/data/prayers/__tests__/resolver.test.js
Labels: merge

#68 fix: Removes Caching for Saved Prayers
  src/data/prayers/resolver.js
Labels: merge

#66 chore: Upgrades to Apollos 1.3.0
  .gitignore
  apollos.json
  config.yml
  package.json
  scripts/link-packages.js
  yarn.lock
Labels: merge

#69 fix: Fixes Live API
  src/data/live/data-source.js
Labels: merge

#70 fix: Puts the Livestream API Back Correctly
  src/data/live/data-source.js
Labels: merge

#72 feat: Adds HLS Livestream URL
  config.yml
  src/data/live/data-source.js
Labels: merge

#73 fix: Fixes Wistia Videos
  config.yml
  src/data/content-items/data-source.js
Labels: merge

#74 chore: Added the CSB Translation
  config.yml
Labels: ready for review

#75 chore: Get Mergify Working
  .mergify.yml
Labels: merge, ready for review

#76 fix: Make Prayer Notifications Work
  src/data/prayers/data-source.js
Labels: merge, ready for review

#78 move appdynamics config to top and change some values
  src/index.js
Labels: merge

#81 chore: Adds Github Actions
  .envExample
  .github/workflows/tests.yml
  .travis.yml
  package.json
Labels: merge

#82 chore: Removes Dockerfile
  Dockerfile
Labels: merge
