Repository NewSpring/crete, pull requests merged in 2020-05, with the labels that each got.

#94 feat: API Ready for Answered Prayer
  src/data/prayers/data-source.js
Labels: merge, ready for review

#96 chore: Upgrade 1.4.0
  apollos.json
  package.json
  src/data/features/data-source.js
  src/data/features/resolver.js
  src/data/features/schema.js
  src/data/index.js
  yarn.lock
Labels: ready for review

#97 fix: Fixes Empty Content Lists
  src/data/matrix-items/__tests__/__snapshots__/data-source.tests.js.snap
  src/data/matrix-items/__tests__/data-source.tests.js
  src/data/matrix-items/data-source.js
Labels: merge

#93 chore: Improves Developer Experience
  package.json
  src/index.js
Labels: merge

#8 fix: (DEV-4300) Fixes Devotionals with Multiple Scriptures
  src/data/content-items/__tests__/__snapshots__/data-sources.tests.js.snap
  src/data/content-items/__tests__/data-sources.tests.js
  src/data/content-items/data-source.js
Labels: merge

#98 chore: Adds Artillery Integration Tests
  .github/workflows/lint.yml
  .github/workflows/loadtest.yml
  .github/workflows/unittest.yml
  loadtests/tests.yml
  loadtests/userFeed.lua
  package.json
  yarn.lock
Labels: merge

#101 chore: Fixed artillery tests
  .github/workflows/artillery.yml
  .github/workflows/jest.yml
Labels: merge

#83 feat: Adds Saving Sermon Notes
  config.yml
  src/data/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  src/data/content-items/__tests__/__snapshots__/data-sources.tests.js.snap
  src/data/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  src/data/content-items/__tests__/data-source.tests.js
  src/data/content-items/__tests__/data-sources.tests.js
  src/data/content-items/__tests__/resolvers.tests.js
  src/data/content-items/data-source.js
  src/data/content-items/resolver.js
  src/data/content-items/schema.js
  src/data/prayers/__tests__/resolver.test.js
Labels: merge

#102 perf: Disable Cache to fix memory leak
  src/data/index.js
Labels: merge

#103 chore: Adds Time to Errors
  src/server.js
Labels: merge

#105 chore: Adds Redis Cache to Server
  package.json
  src/data/index.js
  src/server.js
  yarn.lock
Labels: merge

#106 fix: Fixes Redis
  src/server.js
Labels: merge

#107 chore: Adds script to capture memory dump to S3
  package.json
  scripts/leakdump.js
  yarn.lock
Labels: merge
