Repository NewSpring/crete, pull requests merged in 2020-01, with the labels that each got.

#16 Release 1.6.20
  .codecov.yml
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  config.yml
  package.json
  scripts/generateLocalSchema.sh
  scripts/schemaDiff.sh
  src/bugsnag.js
  src/data/auth/data-source.js
  src/data/authMock.js
  src/data/campusMock.js
  src/data/content-items/__tests__/resolvers.tests.js
  src/data/content-items/resolver.js
  src/data/groups/data-source.js
  src/data/index.js
  src/data/mocks/campus.js
  src/data/mocks/person.js
  src/data/mocks/prayer.js
  src/data/prayer-menu-categories/data-source.js
  src/data/prayer-menu-categories/resolver.js
  src/data/prayer-menu-categories/schema.js
  src/data/prayer-requests/__tests__/__snapshots__/resolver.test.js.snap
  src/data/prayer-requests/__tests__/data-source.test.js
  src/data/prayer-requests/__tests__/resolver.test.js
  src/data/prayer-requests/data-source.js
  src/data/prayer-requests/index.js
  src/data/prayer-requests/schema.js
  src/data/prayers/__tests__/__snapshots__/data-source.test.js.snap
  src/data/prayers/__tests__/__snapshots__/resolver.test.js.snap
  src/data/prayers/__tests__/data-source.test.js
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/index.js
  src/data/prayers/resolver.js
  src/data/prayers/schema.js
  yarn.lock
Labels: merge

#7 chore: Removed React Native Lint Package
  .eslintrc.js
  package.json
  yarn.lock
Labels: merge

#20 chore: Removes Use of Custom Prayer Field
  src/data/prayers/resolver.js
Labels: merge

#21 chore: Adds Pull Request Template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge

#19 (DEV-4290) fix: Fixes Low-Res Videos
  src/data/content-items/data-source.js
Labels: merge

#22 Beta
  .eslintrc.js
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/data/content-items/data-source.js
  src/data/prayers/resolver.js
  yarn.lock
Labels: merge

#23 Release
  .eslintrc.js
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/data/content-items/data-source.js
  src/data/prayers/resolver.js
  yarn.lock
Labels: merge

#12 chore: Adds Better Error Reporting
  package.json
  src/bugsnag.js
  src/server.js
  yarn.lock
Labels: merge

#17 chore: Adds Test Coverage to 'Person'
  src/data/people/__tests__/__snapshots__/resolvers.tests.js.snap
  src/data/people/__tests__/resolvers.tests.js
Labels: merge

#18 chore: Adds Groups Test Coverage
  src/data/groups/__tests__/__snapshots__/data-source.tests.js.snap
  src/data/groups/__tests__/data-source.tests.js
Labels: merge

#24 fix: Fixes Deleting Prayers
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/resolver.js
Labels: merge

#25 fix: Fixes Saving Prayers
  config.yml
Labels: merge

#9 fix: (DEV-4306) Fixes No Photo Error
  src/data/mocks/person.js
  src/data/people/__tests__/__snapshots__/resolvers.tests.js.snap
  src/data/people/__tests__/resolvers.tests.js
  src/data/people/resolver.js
Labels: merge

#27 Beta Release
  config.yml
  package.json
  src/bugsnag.js
  src/data/groups/__tests__/__snapshots__/data-source.tests.js.snap
  src/data/groups/__tests__/data-source.tests.js
  src/data/mocks/person.js
  src/data/people/__tests__/__snapshots__/resolvers.tests.js.snap
  src/data/people/__tests__/resolvers.tests.js
  src/data/people/resolver.js
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/resolver.js
  src/server.js
  yarn.lock
Labels: merge

#28 Production API Release
  config.yml
  package.json
  src/bugsnag.js
  src/data/groups/__tests__/__snapshots__/data-source.tests.js.snap
  src/data/groups/__tests__/data-source.tests.js
  src/data/mocks/person.js
  src/data/people/__tests__/__snapshots__/resolvers.tests.js.snap
  src/data/people/__tests__/resolvers.tests.js
  src/data/people/resolver.js
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/resolver.js
  src/server.js
  yarn.lock
Labels: ready for review

#34 Fixes Internal Server Error
  src/server.js
Labels: ready for review

#26 chore: Adds Simple Load Testing
  loadtests/userFeed.lua
  package.json
Labels: merge

#38 chore: Adds Schema for Paginated Prayers
  src/data/prayers/schema.js
Labels: merge

#32 chore: Better Error Handling
  src/bugsnag.js
  src/server.js
Labels: merge

#39 chore: Publishes Production Schema to Engine in CI
  .travis.yml
  package.json
Labels: merge

#33 Production Release
  apollos.json
  config.yml
  src/data/groups/__tests__/__snapshots__/data-source.tests.js.snap
  src/data/groups/__tests__/data-source.tests.js
  src/data/mocks/person.js
  src/data/people/__tests__/__snapshots__/resolvers.tests.js.snap
  src/data/people/__tests__/resolvers.tests.js
  src/data/people/resolver.js
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/resolver.js
Labels: ready for review

#43 chore: Captures cookies and sends them to bugsnag
  src/data/auth/data-source.js
Labels: merge

#42 chore: Show errors in console
  src/bugsnag.js
  src/server.js
Labels: merge

#45 chore: Server Upgrade to 1.3.0-beta.3
  apollos.json
  local.graphql
  package.json
  yarn.lock
Labels: merge, ready for review
