Repository NewSpring/crete, pull requests merged in 2020-02, with the labels that each got.

#47 chore: Fixes Bugsnag Reporting
  src/server.js
Labels: merge

#41 feat: Adds Prayer Pagination
  config.yml
  src/data/mocks/person.js
  src/data/prayers/__tests__/__snapshots__/resolver.test.js.snap
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/resolver.js
  src/data/prayers/schema.js
Labels: merge

#50 Release
  .travis.yml
  apollos.json
  loadtests/userFeed.lua
  local.graphql
  package.json
  src/bugsnag.js
  src/data/auth/data-source.js
  src/data/prayers/schema.js
  src/server.js
  yarn.lock
Labels: ready for review

#52 chore: Adds Script to Translate Data IDs
  package.json
  scripts/translate.js
Labels: merge

#54 chore: Update API to 1.3.0-beta.6
  apollos.json
  config.yml
  local.graphql
  package.json
  src/server.js
  yarn.lock
Labels: merge, ready for review

#1 chore: Adds Short Link Token Expansion
  src/data/content-items/data-source.js
Labels: ready for review

#56 Beta Release
  apollos.json
  config.yml
  local.graphql
  package.json
  scripts/translate.js
  src/data/content-items/data-source.js
  src/data/mocks/person.js
  src/data/prayers/__tests__/__snapshots__/resolver.test.js.snap
  src/data/prayers/__tests__/resolver.test.js
  src/data/prayers/data-source.js
  src/data/prayers/resolver.js
  src/data/prayers/schema.js
  src/server.js
  yarn.lock
Labels: merge

#49 perf: Improved Performance of Incrementing Prayers
  src/data/prayers/data-source.js
Labels: ready for review

#59 Beta API Release
  src/data/prayers/data-source.js
Labels: ready for review
